### ISSUE TITLE
Router macro does not compile

### ISSUE THREAD

**Issue by ioleo** [cornerman/sloth#148]
Hi,

huge thanks for all the awesome libraries you maintain. I just upgraded my side project to sloth `0.6.3` and I'm getting the compile error from `RouterMacro`:

```
You need to specify the type parameter for the route method explicitly: sloth.Router.apply[java.nio.ByteBuffer, zio.Task](zio.interop.catz.asyncRuntimeInstance[Nothing](zio.interop.catz.implicits.rts)).route[<missing>](contactFormRpc)
```

However my code is (and always was) expicitly providing the type parameter:
```
val router = Router[ByteBuffer, Task]
  .route[ContactFormRpc](contactFormRpc)
  .route[NewsletterRpc](newsletterRpc)
// ...
```

where `contactFormRpc`, `newsletterRpc` are exacly of given type.

Any ideas what could be wrong? I'm using scala `2.13.6`.

**Comment by cornerman** [comment]
Hi @ioleo, thanks for raising this issue!

I feared that this could happen. This error was an idea to protect you from routing to a concrete class instead of a class/trait with abstract methods. Making it more explicit what interface you are exposing.

What I am assuming: `contactFormRpc` is of type `ContactFormRpc` and not a subtype of it. If you would change the type to something more concrete, it should start working. But anyhow, I will remove this warning, as it should not circumvent this use-case.

**Comment by cornerman** [comment]
I have just reverted the commit introducing this check and I started the release of a new version `0.6.4`, which should land on maven soonish.

**Comment by ioleo** [comment]
Thanks. On `0.6.4` it compiles again. Just a bunch of refactorings more and hopefully everything will work at runtime aswell.

**Comment by cornerman** [comment]
Awesome! Please let me knoe if there are any other issues.
