### ISSUE TITLE
Roadmap, release plan?

### ISSUE THREAD

**Issue by ioleo** [cornerman/sloth#15]
Is this library production ready? If not, what is missing? How can I help? Is there any roadmap towards the first release?

I'm currently using autowire for this purpose, but I'd really like to abstract over F and it seems sloth is exacly what I need. However I'm a bit confused about the state of this project.

**Comment by cornerman** [comment]
I am using this library on a production site myself, so I consider it production ready. Furthermore, I have plans to update it further to be even more flexible, but did not come around to finish it yet (see #12) -- but I will eventually. I have not yet release to maven, because the API still might change, but it should work in very similar way as it does now.

If a maven release is important to you, I can publish the current state soonish. Otherwise, you can use jitpack to depend on a specific commit. If you find something unintuitive or have a problem, you can always open an issue and I will try to help and fix bugs. If you have an ideas for an improvement, contributions are very welcome. Just open a PR, then we can discuss and iterate on it :)

**Comment by ioleo** [comment]
I think you could follow [semver 2.0](https://semver.org/) and start publishing to maven pre-1.0 releases, eg. `0.1.0` and hit `1.0.0` once the API is stabilized.

I'd prefer to lock on specific release, to keep things simple, so if it's not a big problem I'd kindly ask you to create a release.

About problems/ideas - I'll definately do. I'll try to switch to sloth sometime this week, so if anything pops up I'll get back to you :)

**Comment by cornerman** [comment]
Great!

I think, you are right with semver -- I will adapt that. I am on holiday right now, but can do a release when I am back next week. I will keep this issue open until then.

**Comment by joan38** [comment]
Hi, Thanks for this I was trying to write that actually: https://github.com/joan38/wireless
I'm trying to get the latest version. Has it been released to maven central?

**Comment by nafg** [comment]
You can consume it via jitpack. For example:

resolvers += "jitpack" at "https://jitpack.io",
libraryDependencies += "com.github.cornerman.sloth" %%% "sloth" %
"34b09cdccb",

**Comment by cornerman** [comment]
I *finally* made the first release :checkered_flag:

You can now get sloth via:
```scala
libraryDependencies += "com.github.cornerman" %%% "sloth" % "0.1.0"
```

**Comment by joan38** [comment]
Thanks @cornerman, that's great!
