### ISSUE TITLE
Id not working as functor

### ISSUE THREAD

**Issue by tballard** [cornerman/sloth#230]
Hi cornerman,

Awesome work. In the long run this library should improve my life, but I've been trying to figure something out and my wife has started to say it will be the death of me;-) Hopefully you can tolerate a stupid question.

I, probably naively, don't understand the point of using Futures on the server. Here's what I'm thinking to myself: The server starts a new thread for every connection, anyway, and it seems intuitively that the Future would have to complete before it can be serialized. I put in a 10 second sleep on the server and yeah, the client blocks for 10 seconds before continuing, as I expected. The only reason for using a Future that I can come up with is that it is a handy way of returning an Either. If so, it seems like there might be a better way that didn't require having to double the size of the thread pool. Also, having the client interface expose a Future might (did) give the false impression that the client could continue working while the Future did its thing. Alternatively, if I'm full of it, a brief explanation in the documentation would be nice for people at my skill level.

Anyway, that being my working theory, and reading that I could use any functor instead of a Future, I have been trying to use the simplest example, a cats.Id. It seems promising, but when it came to "val clientFt = Client[String, Id](IdTransport)", the implicit provided by ClientHandler.flatMapError didn't work for reasons unknown. I spent an embarrassing amount of time on it, but the combination of implicits nested 4 (?) deep and my general lack of understanding has thus far defeated me.

Any enlightenment would be greatly appreciated.

**Comment by cornerman** [comment]
Hi @tballard,

thank you for opening this issue. This is indeed an interesting topic :)

First of all, the issue you are seeing is: on the server-side a `Functor[*]` is sufficient, and `cats.Id` will work. But on the `Client`, you generally need `MonadError[Throwable, *]` - and there is no such instance for `cats.Id`. What you can use for the `Client` is, for example, an `Either[Throwable, *]` - as this has a `MonadError` instance. This is needed because the RPC call from the client can fail, as implemented by the `RequestTransport`.

I say, `MonadError`, but as you already saw, there is actually a less restrictive requirement `FlatMapError` to work with types that do not fullfil `MonadError`. You can have an "unsafe" instance of that for `cats.Id`, but be aware that it will throw an exception on error - which is something we generally try to avoid in functional scala, but it might be what you are after:

```scala
implicit val IdFlatMapError: FlatMapError[cats.Id, Throwable] = new FlatMapError[cats.Id, Throwable] {
  def raiseError[B](failure: Throwable): cats.Id[B] = throw failure
  def flatMapEither[A,B](fa: cats.Id[A])(f: A => Either[Throwable, B]): cats.Id[B] = f(fa).toTry.get
}
```

For the question around `Future` vs `blocking` code. Generally blocking code will occupy a thread, which cannot do any other work while waiting. On the other hand, if you have asynchronous code, the thread can do other work, while the future is not resolved. Though this point does change with project loom in the JVM, because we have green threads now, where you can write asynchronous without using `Future`.

I hope, this helps!

**Comment by tballard** [comment]
Well, that was the most timely response I've ever gotten for anything! Thanks.

**Comment by cornerman** [comment]
Awesome! I am just going to close this issue, but please feel free to reopen or to ask here if something remains unclear :v:

**Comment by tballard** [comment]
Just to make sure we are on the same page with the Future, here is an example showing a Future on the client that is blocking, and I'm not sure what it is buying me. Output is:

Sending request from client at 24
Beginning remote work that takes 10 seconds at 24
This line is right after the request and runs at 34
Done with request at 34

package example

import sloth._

import scala.concurrent.{ExecutionContext, ExecutionContextExecutor, Future}
import chameleon.ext.circe.circeSerializer
import chameleon.ext.circe.circeDeserializer

def printTime(txt: String): Unit =
  println(s"$txt at ${(System.currentTimeMillis() / 1000) % 100}")

trait TomApi {
  def inc(a: Int): Future[Int]
}

object TomApiImpl extends TomApi {
  def inc(a: Int): Future[Int] = {
    printTime("Beginning remote work that takes 10 seconds")
    Thread.sleep(10000L)
    Future.successful(a + 1)
  }
}

object WhyFuture {

  implicit val ec: ExecutionContextExecutor = ExecutionContext.global // yes, it is needed
  object Backend {
    val futureRouter = Router[String, Future]
      .route[TomApi](TomApiImpl)
  }

  def fillFutureRequest(request: Request[String]): Either[ServerFailure, Future[String]] =
    Backend.futureRouter(request)

  def issueFutureRequest(request: Request[String]): Either[ServerFailure, Future[String]] =
    fillFutureRequest(request)

  /** This is where we serialize the request and send it to server */
  object FutureTransport extends RequestTransport[String, Future] {
    override def apply(request: Request[String]): Future[String] =
      issueFutureRequest(request) match {
        case Right(result) => result
        case Left(err) => Future.failed(new Exception(err.toString))
      }
  }

  def main(args: Array[String]): Unit = {
    val clientFt = Client[String, Future](FutureTransport)
    val tomApi = clientFt.wire[TomApi]
    printTime("Sending request from client")
    tomApi.inc(4).onComplete(_ => printTime("Done with request"))
    printTime("This line is right after the request and runs")
    Thread.sleep(1000L)
  }
}

**Comment by cornerman** [comment]
In the client, you are waiting for the response from the router, which is directly calling the `TomApiImpl`. The way you wrote it, there is indeed no advantage in having `Future`, because you are effectively blocking at `Thread.sleep` and then returning `a + 1`.

What that actually means is: while the sleep is happening, this one thread in your application is doing nothing but waiting until the OS wakes it up again. Thus the system cannot use this thread for computing anything else. If you would have just one thread in your application, any parallel request that might come will have to wait for the sleep to finish. An generally, you do not have infinite threads in your JVM (again that changes with project loom using virtual threads instead of kernel threads).

I just saw this blogpost, which might help here. It talks about ZIO in the end, but gives some explanation about blocking and `Thread.sleep` specifically: https://medium.com/@daniel.sebban/how-to-thread-sleep-without-blocking-on-the-jvm-3bc3fac08011

**Comment by tballard** [comment]
So, when we create a Future on the server how to we take advantage of it to run some code while it works? My contention is that it completely runs the code before serializing the Future to send it back to the client. Some things I've read on the internet suggest as much so I totally believe it;-)

**Comment by cornerman** [comment]
I am not entirely sure, what you mean, but yes, the code needs to run before the result can be serialized and sent back to the client.

If you want to work without `Future` in scala, that is viable on the JVM (especially with project loom). And it might make things simpler as well. There are a lot of nice libraries, e.g., in the lihaoyi universe (https://github.com/com-lihaoyi).

A `Future` in scala is a data type to represent some unit of work that is currently run and might not be finished yet. You can `map` and process it asynchronously. Or wait for the result which would be blocking/waiting until that Future is finished. You might want to play around with a fixed `ExecutionContext` to understand a bit better what happens if you only have one or two threads: `ExecutionContext.fromExecutor(Executors.newFixedThreadPool(1))`.

If you look into the direction of `cats-effect` or `ZIO`, you will also find many resources around async programming. Scala offers many ways :+1:

**Comment by tballard** [comment]
Thanks for your patience. My point is that the Future is part of the thing that has gotten run and when sent back and has lost its ability to allow something to run similtaneously, defeating its purpose. Yeah, I'm all about haoyi.

**Comment by tballard** [comment]
Id is fabulous.
